service: pragma-user-service

provider:
  name: aws
  region: us-east-2
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt UsersTable.Arn

        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: !GetAtt UserRegistrationQueue.Arn

        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref UserNotificationTopic

functions:
  getUsers:
    handler: handler.getUsers
    runtime: nodejs20.x
    events:
      - http:
          path: users
          method: get
  postUsers:
    handler: handler.postUsers
    runtime: nodejs18.x
    environment:
      SQS_URL: !Ref UserRegistrationQueue
    events:
      - http:
          path: users
          method: post

  javaHandler:
    handler: com.example.deploy.handler.StreamLambdaHandler
    runtime: java17
    timeout: 29
    package:
      artifact: ../deploy/build/libs/final-build-v1.jar
    events:
      - http:
          path: users
          method: put
      - http:
          path: users/{id}
          method: delete
    
  emailWorker:
    handler: handler.sendEmailWorker
    runtime: nodejs20.x
    environment:
      SNS_TOPIC_ARN: !Ref UserNotificationTopic
    events:
      - sqs:
          arn: !GetAtt UserRegistrationQueue.Arn
          batchSize: 1

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 

    UserRegistrationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UserRegistrationQueue
        VisibilityTimeout: 30
    
    UserNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: UserNotificationTopic